product-ranking/sqs_tests_gui/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from gui.views import LogFileView, CSVDataFileView, AddJob, ProgressMessagesView,\
    ProgressFileView, SearchFilesView, GetS3FileView, SearchS3Cache, \
    RenderS3CachePage, ViewBase64Image, DataViewer
from sqs_stats.views import SQSAutoscaleStats
from kill_servers.views import KillRestoreServersView
from reports.views import ReportSQSJobs, ReportDownloadCSV

from django.conf import settings
from django.conf.urls.static import static

from immediate.views import immediate_run

urlpatterns = [
    # Examples:
    # url(r'^$', 'gui.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^log/(?P<job>[0-9]+)/$', LogFileView.as_view(),
        name='log_file_view'),
    url(r'^data/(?P<job>[0-9]+)/$', CSVDataFileView.as_view(),
        name='csv_data_file_view'),
    url(r'^progress/(?P<job>[0-9]+)/$', ProgressFileView.as_view(),
        name='progress_file_view'),
    url(r'^add-job', csrf_exempt(AddJob.as_view()),
        name='add_job_view'),
    url(r'^view-base64-image/(?P<job>[0-9]+)/$', ViewBase64Image.as_view(),
        name='view_base64_image'),
    url(r'^progress/', ProgressMessagesView.as_view(), name='progress'),
    url(r'^search-files/', SearchFilesView.as_view(), name='search-files'),
    url(r'^get-file/', GetS3FileView.as_view(), name='get-file'),
    url(r'^s3-cache/$', SearchS3Cache.as_view(), name='s3-cache'),
    url(r'^sqs-stats/$', SQSAutoscaleStats.as_view(), name='sqs-stats'),
    url(r'^kill-restore-servers/$', KillRestoreServersView.as_view(), name='kill-restore-servers'),
    url(r'^render-s3-cache/$', RenderS3CachePage.as_view(), name='render-s3-cache'),

    url(r'^reports/sqs-jobs/$', ReportSQSJobs.as_view(), name='report-sqs-jobs'),
    url(r'^reports/get-csv/(?P<encrypted_filename>.+)',
        ReportDownloadCSV.as_view(), name='report-get-csv'),

    url(r'^data/(?P<job>[0-9]+)/viewer/$', DataViewer.as_view(), name='data_file_viewer'),
    url(r'^data/(?P<job>[0-9]+)/viewer/(?P<index>[0-9]+)/$', DataViewer.as_view(), name='data_file_viewer_item'),

    url(r'^immediate/$', login_required(immediate_run), name='immediate'),

    url('^fcgi/$', include('fcgi.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product-ranking/sqs_tests_gui/kill_servers/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


class ProductionBranchUpdate(models.Model):
    branch_to_track = 'sc_production'

    when_updated = models.DateTimeField(default=datetime.datetime.utcnow)

    last_commit_hashsum = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return str(self.when_updated)

    class Meta:
        ordering = ('-when_updated', )


class ServerKill(models.Model):
    branch_update = models.ForeignKey(
        ProductionBranchUpdate, blank=True, null=True)
    manual_restart_by = models.ForeignKey(
        User, blank=True, null=True)
    started = models.DateTimeField(default=datetime.datetime.utcnow)
    finished = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return str(self.started)

product-ranking/sqs_tests_gui/kill_servers/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse

from fcgi.views import AuthViewMixin
from models import ServerKill, ProductionBranchUpdate


class KillRestoreServersView(AuthViewMixin, TemplateView):
    template_name = 'kill_servers.html'

    def get_context_data(self, **kwargs):
        context = super(KillRestoreServersView, self).get_context_data(**kwargs)
        # group server kills by branch update
        context['branch_updates'] = ProductionBranchUpdate.objects.all().order_by(
            '-when_updated').distinct()[0:50]
        context['manual_kills'] = ServerKill.objects.filter(
            manual_restart_by__isnull=False).order_by('-started').distinct()[0:50]
        return context

    def post(self, request, *args, **kwargs):
        if ServerKill.objects.filter(started__isnull=False, finished__isnull=True):
            return HttpResponse('There are already some unfinished ServerKills running!')
        if request.POST.get('button_kill', None):
            return HttpResponse('KILL - this is not implemented yet, nothing happened ;)')
        if request.POST.get('button_restore', None):
            return HttpResponse('RESTORE - this is not implemented yet, nothing happened ;)')
        return HttpResponse('Unrecognized action!')

product-ranking/sqs_tests_gui/kill_servers/templates/kill_servers.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Kill SQS servers</h1>

    <p>{% include 'navigation.html' %}</p>

    <p>All datetimes are in <b>UTC</b>. Only last <b>50</b> records shown in the tables below. </p>

    <table cellpadding="20">
        <tr>
            <td align="center" valign="top">
                <h3>sc_production updates (automatic servers kill)</h3>
                <table cellpadding="10" cellspacing="0" border="1">
                    <tr>
                        <th>Datetime</th>
                        <th>Server kill started</th>
                        <th>Server kill finished</th>
                    </tr>
                    {% for branch_update in branch_updates %}
                        <tr>
                            <td>{{ branch_update.when_updated }}</td>
                            <td>{{ branch_update.serverkill_set.all.0.started }}</td>
                            <td>{{ branch_update.serverkill_set.all.0.finished|default_if_none:"in progress" }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
            <td align="center" valign="top">
                <h3>Manual server kill</h3>
                <table cellpadding="10" cellspacing="0" border="1">
                    <tr>
                        <th>Server kill started</th>
                        <th>Server kill finished</th>
                        <th>Initiated by</th>
                    </tr>
                    {% for manual_kill in manual_kills %}
                        <tr>
                            <td>{{ manual_kill.started }}</td>
                            <td>{{ manual_kill.finished|default_if_none:"in progress" }}</td>
                            <td>{{ manual_kill.manual_restart_by }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
    </table>

    <p>
        <form method="POST" action=".">{% csrf_token %}
            <p><b>You can manually kill all the servers now</b>. The MAX size of the groups will be set to 0.
                You MUST set it back to 100 using the button below, after all the servers are killed
                (you can see the current capacity <a href="{% url 'sqs-stats' %}" target="_blank">here</a>:
                <input type="submit" name="button_kill" value="button_kill" onclick="if(!confirm('ARE YOU SURE YOU WANT TO KILL ALL SERVERS?')) return false;"/>
            </p>
            <p><b>If you have killed all the instances, and you want to restart the capacity</b> of the SC
                autoscale groups, then you have to click this button:
                <input type="submit" name="button_restore" value="button_restore" onclick="if(!confirm('ARE YOU SURE YOU WANT TO RESTORE CAPACITY?')) return false;"/>
            </p>
        </form>
    </p>

</body>
</html>